# CI Performance Configuration
# Defines performance targets and benchmarking parameters for CI/CD pipeline

# Performance Targets (in seconds)
performance_targets:
  format_check: 5.0
  linting: 60.0
  tests: 120.0
  security_audit: 30.0
  release_build: 300.0
  total_ci_time: 515.0

  # Per-platform targets
  platform_targets:
    ubuntu-22.04:
      build_time: 180.0
      test_time: 90.0
    macos-13:
      build_time: 240.0
      test_time: 120.0
    windows-2022:
      build_time: 360.0
      test_time: 150.0

# Benchmarking Configuration
benchmarking:
  # Number of benchmark runs for averaging
  runs: 3

  # Timeout for individual operations (seconds)
  timeouts:
    format_check: 30
    linting: 300
    tests: 600
    security_audit: 180
    build: 900

  # Metrics to collect
  metrics:
    - build_time
    - test_time
    - lint_time
    - format_time
    - security_time
    - binary_size
    - dependency_count
    - cache_hit_rate

  # Output formats
  output_formats:
    - json
    - csv
    - markdown

# CI Optimization Settings
optimization:
  # Caching strategies
  caching:
    rust_cache: true
    cargo_registry: true
    pre_commit: true
    node_modules: false

  # Parallel execution
  parallelism:
    max_jobs: 4
    test_threads: 2
    clippy_jobs: 2

  # Resource limits
  resources:
    memory_limit: "4GB"
    disk_space: "10GB"
    timeout_minutes: 60

# Performance Monitoring
monitoring:
  # Alert thresholds (percentage above target)
  alert_thresholds:
    warning: 20 # 20% above target
    critical: 50 # 50% above target

  # Trend analysis
  trend_analysis:
    window_size: 10 # Number of builds to analyze
    regression_threshold: 15 # Percentage increase to flag as regression

  # Reporting
  reporting:
    frequency: "daily"
    recipients:
      - "ci-team@example.com"
    include_recommendations: true

# Feature-specific Performance Targets
feature_targets:
  ssl:
    build_time: 180.0
    binary_size: 9437184 # 9MB (rustls implementation)
  minimal:
    build_time: 120.0
    binary_size: 6291456 # 6MB

# Cross-platform Considerations
cross_platform:
  # Platform-specific optimizations
  ubuntu:
    use_sccache: true
    parallel_jobs: 4
  macos:
    use_sccache: false
    parallel_jobs: 2
  windows:
    use_sccache: false
    parallel_jobs: 2
    git_fetch_cli: true

# Quality Gates
quality_gates:
  # Performance requirements for merge
  merge_requirements:
    max_build_time: 600 # 10 minutes
    max_test_time: 300 # 5 minutes
    max_total_time: 900 # 15 minutes

  # Performance regression detection
  regression_detection:
    enabled: true
    baseline_builds: 5
    threshold_percentage: 25

# Tool-specific Configuration
tools:
  actionlint:
    enabled: true
    version: "latest"

  act:
    enabled: true
    docker_image: "catthehacker/ubuntu:act-22.04"
    platform: "ubuntu-22.04=catthehacker/ubuntu:act-22.04"

  cargo_nextest:
    enabled: true
    parallel: true
    retries: 2

  cargo_llvm_cov:
    enabled: true
    format: "lcov"
    ignore_filename_regex: "tests/"

# Notification Settings
notifications:
  performance_alerts:
    enabled: true
    channels:
      - slack
      - email

  benchmark_reports:
    enabled: true
    schedule: "0 6 * * 1" # Weekly on Monday at 6 AM
    format: "markdown"

# Archive Settings
archival:
  benchmark_data:
    retention_days: 90
    compress: true

  performance_reports:
    retention_days: 365
    format: "json"
