# CI-specific deny.toml with strict enforcement
# This file is used in CI environments to enforce strict security policies

# Root options
[graph]
targets = []
all-features = false
no-default-features = true
features = ["json", "csv", "ssl", "additional_mysql_types", "verbose"]

[output]
feature-depth = 1

[advisories]
# Strict enforcement for CI - yanked crates are denied
yanked = "deny"
ignore = []

[licenses]
allow = [
    "MIT",
    "Apache-2.0",
    "Apache-2.0 WITH LLVM-exception",
    "BSD-2-Clause",
    "BSD-3-Clause",
    "CC0-1.0",
    "ISC",
    "Unicode-DFS-2016",
    "Unicode-3.0",
    "Unlicense",
    "0BSD",
    "OpenSSL",                        # required by aws-lc-sys (via aws-lc-rs used by rustls)
    "CDLA-Permissive-2.0",            # required by webpki-roots (TLS CA roots)
]
confidence-threshold = 0.8
exceptions = []

[licenses.private]
ignore = false
registries = []

[bans]
multiple-versions = "warn"
wildcards = "warn"
highlight = "all"
workspace-default-features = "allow"
external-default-features = "allow"
allow = []
deny = []

skip = []
skip-tree = []

[sources]
unknown-registry = "warn"
unknown-git = "warn"
allow-registry = ["https://github.com/rust-lang/crates.io-index"]
allow-git = []

[sources.allow-org]
github = []
gitlab = []
bitbucket = []
