name: "Build Dependencies"
description: "Build project dependencies with specified feature combinations"

inputs:
  features:
    description: "Feature combinations to build (comma-separated)"
    required: false
    default: "native-tls,rustls,none"

runs:
  using: composite
  steps:
    - name: Build Dependencies
      shell: bash
      run: |
        IFS=',' read -ra FEATURES <<< "${{ inputs.features }}"

        for feature in "${FEATURES[@]}"; do
          case "$feature" in
            "native-tls")
              echo "ðŸ”¨ Building with native-tls (ssl feature)..."
              cargo check --all-targets --no-default-features --features "json csv ssl additional_mysql_types verbose"
              ;;
            "rustls")
              echo "ðŸ”¨ Building with rustls (ssl-rustls feature)..."
              cargo check --all-targets --no-default-features --features "json csv ssl-rustls additional_mysql_types verbose"
              ;;
            "none")
              echo "ðŸ”¨ Building without TLS features..."
              cargo check --all-targets --no-default-features --features "json csv additional_mysql_types verbose"
              ;;
            *)
              echo "âš ï¸ Unknown feature: $feature"
              ;;
          esac
        done
