name: "Run Tests"
description: "Run cargo tests with specified feature combinations"

inputs:
  features:
    description: "Feature combinations to test (comma-separated)"
    required: false
    default: "native-tls,rustls,none"
  use-nextest:
    description: "Whether to use nextest for testing"
    required: false
    default: "true"

runs:
  using: composite
  steps:
    - name: Run Tests
      shell: bash
      run: |
        IFS=',' read -ra FEATURES <<< "${{ inputs.features }}"

        for feature in "${FEATURES[@]}"; do
          case "$feature" in
            "native-tls")
              echo "ðŸ§ª Testing with native-tls (ssl feature)..."
              if [[ "${{ inputs.use-nextest }}" == "true" ]]; then
                cargo nextest run --no-default-features --features "json csv ssl additional_mysql_types verbose" || cargo test --no-default-features --features "json csv ssl additional_mysql_types verbose"
              else
                cargo test --no-default-features --features "json csv ssl additional_mysql_types verbose"
              fi
              ;;
            "rustls")
              echo "ðŸ§ª Testing with rustls (ssl-rustls feature)..."
              if [[ "${{ inputs.use-nextest }}" == "true" ]]; then
                cargo nextest run --no-default-features --features "json csv ssl-rustls additional_mysql_types verbose" || cargo test --no-default-features --features "json csv ssl-rustls additional_mysql_types verbose"
              else
                cargo test --no-default-features --features "json csv ssl-rustls additional_mysql_types verbose"
              fi
              ;;
            "none")
              echo "ðŸ§ª Testing without TLS features..."
              if [[ "${{ inputs.use-nextest }}" == "true" ]]; then
                cargo nextest run --no-default-features --features "json csv additional_mysql_types verbose" || cargo test --no-default-features --features "json csv additional_mysql_types verbose"
              else
                cargo test --no-default-features --features "json csv additional_mysql_types verbose"
              fi
              ;;
            *)
              echo "âš ï¸ Unknown feature: $feature"
              ;;
          esac
        done
