name: Deploy Documentation

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]
    workflow_dispatch:

permissions:
    contents: read
    pages: write
    id-token: write

defaults:
    run:
        shell: bash

concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: false

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
            - uses: jdx/mise-action@c2a87611a18de5b3828c5652fe268e992400cb5c # v4.3.0
              with:
                  install: true
                  cache: true
                  github_token: ${{ secrets.GITHUB_TOKEN }}

            - name: Setup mdBook
              uses: jontze/action-mdbook@6c0be56d14c4bf16861b00af61f50ff7400ce502 # v4.0.0
              with:
                  token: ${{ secrets.GITHUB_TOKEN }}
                  mdbook-version: "0.5.2"
                  use-mermaid: true
                  use-toc: true
                  use-admonish: true
            - name: Install mdbook plugins
              run: cargo binstall mdbook-tabs mdbook-i18n-helpers mdbook-alerts mdbook-yml-header mdbook-image-size --no-confirm

            - name: Build mdBook
              run: |
                  cd docs
                  mdbook build

            - name: Build rustdoc and copy into book
              run: |
                  set -e
                  cargo doc --no-deps --document-private-items --target-dir target
                  mkdir -p docs/book/api
                  cp -r target/doc/* docs/book/api/

            - name: Setup Pages
              if: github.ref == 'refs/heads/main'
              uses: actions/configure-pages@45bfe0192ca1faeb007ade9deae92b16b8254a0d # v6.0.0

            - name: Upload artifact
              if: github.ref == 'refs/heads/main'
              uses: actions/upload-pages-artifact@fc324d3547104276b827a68afc52ff2a11cc49c9 # v5.0.0
              with:
                  path: docs/book

    deploy:
        if: github.ref == 'refs/heads/main'
        environment:
            name: github-pages
            url: ${{ steps.deployment.outputs.page_url }}
        runs-on: ubuntu-latest
        needs: build
        steps:
            - name: Deploy to GitHub Pages
              id: deployment
              uses: actions/deploy-pages@368f82528645a54fb793d4d04e342629a3f51346 # v5.0.1
